version: "3"

services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=python-db"
      - "POSTGRES_PASSWORD=python-pw"
      - "POSTGRES_USER=python-user"
    networks:
      - emotionDetect

  backend:
    build:
      context: ./EDbackend
    command: sh -c "
      ls -l &&
      cd EDbackend &&
      ls -l &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 EDbackend.wsgi:application"
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - emotionDetect

  frontend:
    build:
      context: ./front
    volumes:
      - react_build:/react/build
    networks:
      - emotionDetect

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
    networks:
      - emotionDetect

volumes:
  react_build:

networks:
  emotionDetect:
