# Generated by Django 4.2 on 2023-08-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
